# Generated by Django 3.2.20 on 2023-08-02 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_us', '0002_auto_20230802_1357'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUsForm',
            new_name='ContactUs',
        ),
    ]
